/*
   Obfuscated by COBF (Version 1.06 2006-01-07 by BB) at Wed Apr 15 13:40:18 2009
*/
#define l121 typedef
#define l124 enum
#define l70 SDD_READ_MISS
#define l61 SDD_READ_MISS_FORWARD
#define l44 SDD_READ_MISS_REPLY_DATA
#define l49 SDD_WRITE_HIT_UPDATE_DATA
#define l64 SDD_WRITE_MISS
#define l58 SDD_WRITE_MISS_FORWARD
#define l51 SDD_WRITE_MISS_REPLY
#define l46 SDD_WRITE_MISS_REPLY_DATA
#define l52 SDD_WRITE_MISS_UPDATE_MEM
#define l41 SDD_INVALIDATE_FORWARD
#define l65 SDD_READ_DATA_REPLY_DEFER
#define l60 SDD_WRITE_DATA_REPLY_DEFER
#define l30 COHERENCE_MSG
#define l55 extern
#define lb unsigned
#define la int
#define l110 NETWORK_DEBUG
#define l72 input_link_width
#define l62 input_virtual_channels
#define l69 input_buffers_per_vc
#define lw void
#define l131 print_msg
#define l132 get_message_count
#define l161 float
#define l135 get_ave_message_latency
#define l105 network_register
#define lv network_enqueue
#define l102 network_dequeue
#define l101 network_tick
#define l117 final_hook
#define lh struct
#define l83 signed
#define l27 char
#define l22 double
#define lu static
#define l3 inline
#define l174 const
#define l166 va_list
#define l163 va_start
#define l178 vfprintf
#define l25 stderr
#define l153 va_end
#define l98 exit
#define l29 logb
#define l9 return
#define lq printf
#define l7 for
#define l17 NULL
#define ll if
#define lg break
#define l160 do
#define ln assert
#define l24 else
#define l43 while
#define l56 memset
#define l35 sizeof
#define l80 switch
#define lk case
#define l88 default
#define l171 FILE
#define l167 fopen
#define l173 fscanf
#define l142 EOF
#define l172 strcmp
#define l175 fclose
#define l116 calloc
#define l169 malloc
#define l28 fprintf
#define l164 main
#define l18 optarg
#define l168 getopt
#define l140 strcpy
#define l31 atoi
#define l151 atof
#define l165 memcpy
#define l170 sprintf
#define l154 continue
