#include "cfortran.h"

const char* dgemm_desc = "BLAS dgemm.";

PROTOCCALLSFSUB13(DGEMM,dgemm,STRING,STRING,INT,INT,INT,DOUBLE,DOUBLEV,INT,DOUBLEV,INT,DOUBLE,DOUBLEV,INT)
#define BLAS_DGEMM(TRANSA,TRANSB,M,N,K,ALPHA,A,LDA,B,LDB,BETA,C,LDC) CCALLSFSUB13(DGEMM,dgemm,STRING,STRING,INT,INT,INT,DOUBLE,DOUBLEV,INT,DOUBLEV,INT,DOUBLE,DOUBLEV,INT,TRANSA,TRANSB,M,N,K,ALPHA,A,LDA,B,LDB,BETA,C,LDC)

void
square_dgemm (const int M, 
              double *A, double *B, double *C)
{
  BLAS_DGEMM ("N","N", M,M,M, 1.0, A,M, B,M, 0.0, C,M);
}
